name: Tasks App - Deploy angular web app to firebase hosting

on:
  push:
    branches:
      - main

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Test's
        run: npm run test:ci

      - name: Install CLI Firebase
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Cloud Functions
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
